### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by joppekoers** [nloomans/Codam.app#15]
Isn't it time to deprecate this project now that Freek updated and added to the Software Center?

This repo spams my GitHub feed.

**Comment by joppekoers** [comment]
@nloomans

**Comment by EuanHoll** [comment]
I'll hit up @nloomans and see, but from my experience, the Software Centre doesn't stay updated for long. For now, unsubscribe from the notification of the repo.

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/managing-your-subscriptions
