### ISSUE TITLE
Application Request: KeepassXC.app

### ISSUE THREAD

**Issue by potjesoep** [nloomans/Codam.app#3]
**Website URL:** https://keepassxc.org/
**Brew install command (if available)**: brew cask install keepassxc

thank u

**Comment by nloomans** [comment]
Hey, I added KeepassXC in the pre-release [v0.3.0-rc1](https://github.com/nloomans/Codam.app/releases/tag/v0.3.0-rc1) (commit cfc53c77). Could you test if this works?

**Comment by nloomans** [comment]
Resolved with release [v.0.3.0](https://github.com/nloomans/Codam.app/releases/tag/v0.3.0)
