### ISSUE TITLE
Application Request: ObinsKit.app

### ISSUE THREAD

**Issue by potjesoep** [nloomans/Codam.app#7]
**Website URL:** http://en.obins.net/
**Brew install command (if available)**: wget http://releases.obins.net/occ/darwin/x64/ObinsKit_1.1.1_x64.dmg

**Comment by nloomans** [comment]
Could you test if [v0.4.0-alpha3](https://github.com/nloomans/Codam.app/releases/tag/v0.4.0-alpha3) works?

**Comment by potjesoep** [comment]
It works! thank you 👍
