### ISSUE TITLE
Application Request: Alacritty.app

### ISSUE THREAD

**Issue by VictorTennekes** [nloomans/Codam.app#9]
Would be a nice addition if possible :) very nice to use when u want to use only dotfiles for config :)

**Website URL:** https://github.com/alacritty/alacritty
**Brew install command (if available)**: brew cask install alacritty

**Comment by potjesoep** [comment]
if you build it from source, it spits out a .app

**Comment by VictorTennekes** [comment]
Ah, guess I should RTFM haha ty :)
